/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-10 23:01:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Bank Management System - Signup2</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/signup2.css\">\r\n");
      out.write("<script>\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var aadhar = document.getElementById(\"aadhar\").value;\r\n");
      out.write("        if (aadhar.length !== 12) {\r\n");
      out.write("            alert(\"Aadhar number must be 12 digits.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <form action=\"Signup2Servlet\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("            <input type=\"hidden\" name=\"formno\" value=\"");
      out.print( request.getParameter("formno") );
      out.write("\">\r\n");
      out.write("            <label for=\"religion\">Religion:</label>\r\n");
      out.write("            <select id=\"religion\" name=\"religion\">\r\n");
      out.write("                <option value=\"Hindu\">Hindu</option>\r\n");
      out.write("                <option value=\"Muslim\">Muslim</option>\r\n");
      out.write("                <option value=\"Sikh\">Sikh</option>\r\n");
      out.write("                <option value=\"Christian\">Christian</option>\r\n");
      out.write("                <option value=\"Other\">Other</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("            <label for=\"category\">Category:</label>\r\n");
      out.write("            <select id=\"category\" name=\"category\">\r\n");
      out.write("                <option value=\"General\">General</option>\r\n");
      out.write("                <option value=\"OBC\">OBC</option>\r\n");
      out.write("                <option value=\"SC\">SC</option>\r\n");
      out.write("                <option value=\"ST\">ST</option>\r\n");
      out.write("                <option value=\"Other\">Other</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("            <label for=\"income\">Income:</label>\r\n");
      out.write("            <select id=\"income\" name=\"income\">\r\n");
      out.write("                <option value=\"Null\">Null</option>\r\n");
      out.write("                <option value=\"<1,50,000\">&lt;1,50,000</option>\r\n");
      out.write("                <option value=\"<2,50,000\">&lt;2,50,000</option>\r\n");
      out.write("                <option value=\"5,00,000\">5,00,000</option>\r\n");
      out.write("                <option value=\"Uptp 10,00,000\">Uptp 10,00,000</option>\r\n");
      out.write("                <option value=\"Above 10,00,000\">Above 10,00,000</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("            <label for=\"education\">Education:</label>\r\n");
      out.write("            <select id=\"education\" name=\"education\">\r\n");
      out.write("                <option value=\"Non-Graduate\">Non-Graduate</option>\r\n");
      out.write("                <option value=\"Graduate\">Graduate</option>\r\n");
      out.write("                <option value=\"Post-Graduate\">Post-Graduate</option>\r\n");
      out.write("                <option value=\"Doctrate\">Doctrate</option>\r\n");
      out.write("                <option value=\"Others\">Others</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("            <label for=\"occupation\">Occupation:</label>\r\n");
      out.write("            <select id=\"occupation\" name=\"occupation\">\r\n");
      out.write("                <option value=\"Salaried\">Salaried</option>\r\n");
      out.write("                <option value=\"Self-Employed\">Self-Employed</option>\r\n");
      out.write("                <option value=\"Business\">Business</option>\r\n");
      out.write("                <option value=\"Student\">Student</option>\r\n");
      out.write("                <option value=\"Retired\">Retired</option>\r\n");
      out.write("                <option value=\"Other\">Other</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("            <label for=\"pan\">PAN Number:</label>\r\n");
      out.write("            <input type=\"text\" id=\"pan\" name=\"pan\"><br><br>\r\n");
      out.write("            <label for=\"aadhar\">Aadhar Number:</label>\r\n");
      out.write("            <input type=\"text\" id=\"aadhar\" name=\"aadhar\"><br><br>\r\n");
      out.write("            <label for=\"seniorCitizen\">Senior Citizen:</label>\r\n");
      out.write("            <input type=\"radio\" id=\"yes\" name=\"seniorCitizen\" value=\"Yes\">\r\n");
      out.write("            <label for=\"yes\">Yes</label>\r\n");
      out.write("            <input type=\"radio\" id=\"no\" name=\"seniorCitizen\" value=\"No\">\r\n");
      out.write("            <label for=\"no\">No</label><br><br>\r\n");
      out.write("            <label for=\"existingCustomer\">Existing Customer:</label>\r\n");
      out.write("            <input type=\"radio\" id=\"yes\" name=\"existingCustomer\" value=\"Yes\">\r\n");
      out.write("            <label for=\"yes\">Yes</label>\r\n");
      out.write("            <input type=\"radio\" id=\"no\" name=\"existingCustomer\" value=\"No\">\r\n");
      out.write("            <label for=\"no\">No</label><br><br>\r\n");
      out.write("            <button type=\"submit\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
